### ISSUE TITLE
Adding New Test Case - oversized image file upload

### ISSUE THREAD

**Issue by 0xmaximus** [OWASP/wstg#1018]
**What would you like added?**
**Pixel/Frame flood attack**

Would you like to be assigned to this issue?

- [ ] Assign me, please!

**Comment by kingthorin** [comment]
Got a reference?

**Comment by 0xmaximus** [comment]
https://github.com/0xmaximus/Galaxy-Bugbounty-Checklist/tree/main/DOS#4-pixel-floodimage-with-a-huge-pixelsframe-floodgif-with-a-huge-frame-attack

and Hackerone reports.

**Comment by kingthorin** [comment]
It should be added to a section such as: https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md

I’d be surprised if the guide doesn’t already have a bit on image processing but I don’t currently have a convenient way to check (on my cell phone).

**Comment by rbsec** [comment]
@kingthorin  we probably need to be a bit careful about how big that section gets - because any file type that you upload and the server processes can potentially have vulnerabilities (especially DoS). Image upload is probably a common enough format that it's worth including as a specific section (although it's technical covered in the "other file formats").

**Comment by 0xmaximus** [comment]
Great!
Ready to add.
