### ISSUE TITLE
Update Privilege Escalation's Weak SessionID Section

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#1130]
**What's the issue?**
[Privilege Escalation guide](https://github.com/OWASP/wstg/blob/a6c4017207a10ddccbb4eeb770b0ce8873008060/document/4-Web_Application_Security_Testing/05-Authorization_Testing/03-Testing_for_Privilege_Escalation.md) contains a section at the end called Weak SessionID that feels a bit out of place and could take a rewrite

**How do we solve it?**
See if the section is still required, if it can be merged into other sections, or if it simply needs a better rewrite to belong to the rest of the content

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [ ] Assign me, please!

**Comment by Lucas-Schmucas** [comment]
I would be happy to help. Could you assign me, please?
I can't add a check to the little box, unfortunately :(

**Comment by Lucas-Schmucas** [comment]
I think the section “Weak SessionID” is already described in great detail in [WSTG-SESS-01 - Session Analysis](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/06-Session_Management_Testing/01-Testing_for_Session_Management_Schema.md#session-analysis). It is therefore not necessary to move it, which is why I have removed it.
