### ISSUE TITLE
Add tests to 4.12.9 Testing for Clickjacking

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#183]
The current document describes clickjacking defenses from the title "Client side protection: Frame Busting" onward. Much of the content also appears in [OWASP Clickjacking Defense Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html).

There is a "proof of concept" described later in the text, but no specific testing instructions. I believe the portion of the document from the title "Client side protection: Frame Busting" onward should be rewritten without defense recommendations (out of scope of the testing guide) and with specific testing instructions.

**Comment by Hsiang-Chih** [comment]
"4.12.9 Testing for Clickjacking"
For the testing instructions, I think, it was provided. i.e. below. 
Do you mean instead of the whole section description, it's suggested to list step 1, step 2....?

**Suggested Tests**
Step 1: Create a HTML "ClickJacking.html" with your target testing website as below.

   <body>
        <iframe src="http://www.target.site" width="500" height="500"></iframe>
    </body>

Step 2: Use Browser to open the  "ClickJacking.html"
Step 3: Review if the target website can be shown in the HTML  "ClickJacking.html"
If the target website can be shown in the "ClickJacking.html", then the target website is vulnerable to clickJacking.

**Original Text**

<html>
    <head>
        <title>Clickjack test page</title>
    </head>
    <body>
        <iframe src="http://www.target.site" width="500" height="500"></iframe>
    </body>
</html>

If the http://www.target.site page is successfully loaded into the frame, then the site is vulnerable and has no type of protection against clickjacking attacks.

**Comment by monalisha31** [comment]
@kingthorin can i work on this issue?

**Comment by kingthorin** [comment]
Sure, go for it.

**Comment by nikhil-anilkumar** [comment]
I will work on this.

**Comment by doverh** [comment]
@kingthorin I created a PR with an initial suggestion to refactor Clickjacking section. I will collect reviews and advance on my research with your help.
