### ISSUE TITLE
new content - test cloud storage (mainly on Amazon S3)

### ISSUE THREAD

**Issue by jeremychoi** [OWASP/wstg#328]
**What would you like added?**
Briefly describe the topic of the new content. Is this a new section or an addition to an existing topic?

This is a new section under configuration category (i.e. could be 4.3.11?). The topic is about **testing cloud storage** mainly focusing on testing Amazon S3 bucket misconfiguration.

A brief intro - a part of the whole section what I've already written:

Cloud storage services facilitate Web application and services to store and access objects in the storage service. Improper access control configuration, however, may result in sensitive information exposure, data being tampered, or unauthorized access.

Would you like to be assigned to this issue?
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by jeremychoi** [comment]
I just saw https://github.com/OWASP/wstg/issues/14 include Amazon AWS bucket service. Has any draft been written for it? I've finished a draft of mine. Can I get any guidance on how to proceed?

**Comment by kingthorin** [comment]
I think it's fine for you to proceed, I haven't heard of any movement on 14 and they can always add to your content if necessary (or propose to move it if there's a good reason to).

4.3.11 seems fine to me.

**Comment by jeremychoi** [comment]
ok thanks :) PR - https://github.com/OWASP/wstg/pull/329

**Comment by tolo7010** [comment]
Hi team! since #14 is a main section for testing integration / third party service (it should be 4.3.11). As you said we need collaboration and I will provide general information / overall about how 3rd party applications (cloud / installed) could be misused, but each individual technology should be added by someone who really getting used (expert) at it. The specific detail of each technology (Amazon S3 for this issue) should be a sub-section of #14, e.g: 4.3.11.1. Thank you @jeremychoi for the contribution!

**Comment by tolo7010** [comment]
For future PR, anything about 3rd party integration (cloud / local-install / embedded scripts, ...) such as issue tracker, customer support channel, etc...) should also be added to be well-organized

**Comment by tolo7010** [comment]
Because technology changes every day, I think we need one dedicated section for this and add a sub-section for each new technology in the future.

**Comment by jeremychoi** [comment]
thanks @tolo7010. For me, either each having a separate topic(each could have more general concepts like the way I did for Amazon S3: e.g. amazon S3 - test cloud storage. For another example, writing a topic as test CDN for Cloudflare) or having an integrated one with sub sections is fine.

**Comment by tolo7010** [comment]
Hi @jeremychoi , first of all thanks for the AWS stuff! I understand your point but I am trying to think about expansion in the future. We should categorized what company uses as part of thair business and it doesn't limit to only AWS, for example:
- Cloud service (S3, storage, vpn, cdn) ...
- Git repo hosting (i.e: data leak, misconfig read/wire permission).
- Embeded javsscripts and / or API/SDK calls for external products.
- Etc.

Note that some of the above need only a few paragraphs but it worth to be mentioned, for example, make sure XSS are properly filtered for asset import via API calls, etc...

As I am not an expert in every fields, so I believe we should dedicate a main sub-section, the only goal for this is to make the guide organized. Rather than we have:

4.3.11. AWS
4.3.11.1. S3
4.3.11.2. Storage
4.3.12. CloudFlare
4.3.13. GitHub
4.3.14. GitLab
4.3.15. Zendesk
4.3.16. ...

As the times go by, I believe in the future new products / new technologies will be released and (possibly) existing products from company XYZ will be outdated. Additionally, I am not recommended we put company name to the main section (for example Amazon and Google are offering the same services). What I try to suggest is to organize this section into category of feature types, for example:

4.3.11. Testing for integrating / third party services
  4.3.11.1. Cloud Computing
     - Amazon S3, CDN...
  4.3.11.2. Development Control
     - Git, ...
  4.3.11.3. Issue Tracking
     - Jira, ...
  ...

As I stated this is just to organize this section (and I believe this will be the largest OSTG section)

**Comment by ThunderSon** [comment]
It is true.
4.3.11 isn't the final ID that's for sure. It's just something to keep the work going.
We'll make sure to update you with how we'll be moving forward with this. If you have any additional updates on how you see this (other than the last comment in this thread), share with us in order to take them into consideration. We'll update this issue to reflect what we're thinking as well as a team.

**Comment by victoriadrake** [comment]
> 4.3.11. Testing for integrating / third party services
> 4.3.11.1. Cloud Computing
> - Amazon S3, CDN...
> 4.3.11.2. Development Control
> - Git, ...
> 4.3.11.3. Issue Tracking
> - Jira, ...
> 4.3.11.4. Customer Support
> - Zendesk, ...
> 4.3.11.5. Payment System

@tolo7010 This would be my preference as well.

The WSTG is currently a living thing here on GitHub, so I’m not concerned about getting the organization perfect before we have the relevant material. My preference is to focus on the new content coming in, and organizing the sections second. I’m looking forward to #14!
