### ISSUE TITLE
SQL Injection Specific Tests Non-Uniform Titles

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#352]
**What's the issue?**
SQL Injection specific test cases have random Titles and are not uniform in any way.

**How do we solve it?**
Titles should be uniform. They need to follow that they are under Input Validation, SQL Injection, and by that, their names become clear to what they actually are.
I'll leave the naming to @victoriadrake or @kingthorin as they are more fit to name things.

**Comment by victoriadrake** [comment]
@ThunderSon Which section are you referring to? [This](https://github.com/OWASP/wstg/blob/4f8198d57d0359774471d2e49175bb7df0a117b1/document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5_Testing_for_SQL_Injection_WSTG-INPVAL-005.md)?

**Comment by ThunderSon** [comment]
I am discussing all the tests that follow after SQL Injection (MSSQL, MySQL, etc.). They don't have a naming convention, they are just thrown randomly based on the author's discretion.

**Comment by victoriadrake** [comment]
Ah. This will be addressed in #253 and the [proposed v5 layout](https://github.com/OWASP/wstg/pull/254/files?short_path=2312a8f#diff-2312a8ff16d1c93b4d27c19f549d6ec9) that has the tests alphabetized.

We're addressing it in v5 because changing the order of the sections will introduce the breaking change of different section numbers.
