### ISSUE TITLE
Review and fix HTTP POST request examples (4.5.1)

### ISSUE THREAD

**Issue by rbsec** [OWASP/wstg#369]
There are a number of example POST requests in 4.5.1 (Testing for Credentials Transported over an Encrypted Channel), such as the one below:

```
POST http://www.example.com/homepage.do
Host: http://www.example.com/homepage.do
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.8.1.14) Gecko/20080404
Accept: text/xml,application/xml,application/xhtml+xml,text/html
Accept-Language: it-it,it;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip,deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Keep-Alive: 300
Connection: keep-alive
Referer: http://www.example.com/homepage.do
Cookie: SERVTIMSESSIONID=s2JyLkvDJ9ZhX3yr5BJ3DFLkdphH0QNSJ3VQB6pLhjkW6F
Content-Type: application/x-www-form-urlencoded
Content-length: 45

User=test&Pass=test&portal=ExamplePortal
```

There are a few things wrong with this:

- The first line is invalid (the protocol and hostname shouldn't be here, and it's missing the `HTTP/1.1`)
- The `Host` header is invalid (shouldn't have the protocol or the path)
- There's a lot of noise (useragent, encoding, charset, etc) that distracts from the important bits.

I'm sure there are similar issues elsewhere. I understand the intention is to make it clear that it's HTTP rather than HTTPS, but it's not good to be giving example requests that are completely invalid.

Perhaps this could be presented more simply as something like:

POST https://example.org/homepage.do
```
User=test&Pass=test&portal=ExamplePortal
```

Or if a few the headers are relevant:

POST https://example.org/homepage.do
```
Host: www.example.org
Foo: bar
[...]

User=test&Pass=test&portal=ExamplePortal
```

Thoughts?

**Comment by kingthorin** [comment]
Closer to option two would be my choice.

Include the method/verb in the code block, correct the host header, and provide some realistic/relevant header fields.

**Comment by ThunderSon** [comment]
Yeah, something like this:
```
POST /homepage.do HTTP/1.1
Host: example.org
Foo: bar
[...]

User=test&Pass=test&portal=ExamplePortal
```
Your examples had a mismatch between host and domain, but I'll let that go for now 😛

**Comment by ThunderSon** [comment]
Hmm, we'll need to set this under a milestone. How about we look at later versions, prior to releasing v5 maybe, or after getting over with the more critical versions, say till 4.3 the least?

**Comment by rbsec** [comment]
@ThunderSon the only issue with that approach is that it doesn't show the protocol. A lot of the time it's irrelevant, but in 4.5.1 (for example) it's talking about HTTP vs HTTPS in some of the issues, so there would need to be some thought about how to display that.

Also the `Host` header can probably be removed - unless it's relevant to the issue there's not much point having a `Host` header that points to an example domain. Most of the time I'd imagine you don't really need any headers.

**Comment by rbsec** [comment]
Also, if when a decision is made on how GET/POST requests should be shown, it might be worth updating the style guide with it.

**Comment by ThunderSon** [comment]
Valid point. `Host` is required in `HTTP/1.1`, so I'd prefer keeping it.

Good note about the style guide. @kingthorin we had a discussion on this same topic, guess we missed the bad examples and focused on some other semantics back then.

**Comment by rbsec** [comment]
@ThunderSon that's fair. Personally I tend to remove it when I report stuff as it's just noise, but I can see the value to keeping the requests valid.

**Comment by patrickceg** [comment]
I know the issue is looking specifically at the HTTP requests, but I see issues with the article as a whole if I read it as just someone wanting to test for the problem.

I assume this is the article? 
https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/04-Authentication_Testing/01-Testing_for_Credentials_Transported_over_an_Encrypted_Channel.md#how-to-test

---

For the header and black box testing

> How to Test
> Black-Box Testing
> In the following examples we will use a web proxy in order to capture packet headers and to inspect them. You can use any web proxy that you prefer.
[Examples start]

Now read that as if you are just someone who wants to test... You still have not told the person how to test it! Don't we need something like:

> How to Test
To test for credentials being sent insecurely, use a web browser with web developer tools debuggers enabled or an intercepting proxy including OWASP ZAP while you log in.
> Black Box Testing
....

The other issue is that for some reason, the "Good" and "Bad" cases aren't really outlined. I barely know if "Example 2" is good or not because of how it's buried ... as the second example.

Wouldn't we rather structure it something like this?


* Black Box Testing
    * Logging in with proxy or debugger enabled
        * Expected result: Entire login is POST body over HTTPS
        * Bad result 1: Credential sent with POST body over HTTP
        * Bad result 2: Any credential sent through URL (regardless of method or transport mechanism)
    * If page is reachable by HTTP and HTTPS, attempt to force credentials over HTTP by replaying the POST request over HTTP

---

Grey box testing is also weird... it looks more like it should be "Remediation"

> Speak with the developers of the web application and try to understand if they are aware of the differences between HTTP and HTTPS protocols and why they should use HTTPS for transmitting sensitive information. Then, check with them if HTTPS is used in every sensitive request, like those in log in pages, to prevent unauthorized users to intercept the data.

If I was to write a Grey box testing, I'd probably phrase it like this:

: If testers have access to the server configuration, verify that server is configured to reject plain HTTP requests containing any credentials.

I'm not too familiar with web server configurations, but I know that you can set certain cookies to only be sent over HTTPS. I'm not sure if there's a security header in pages that forces the browser to fail out if you attempt to force HTTP. That said, honestly in 2020 when web browsers give you the red warning for any HTTP and a Raspberry Pi can server HTTPS, I'd be tempted to just say to verify the server is configured that the only thing it will do if you give it any HTTP is to redirect you to HTTPS...
