### ISSUE TITLE
addition to  "The Web Security Testing Framework"

### ISSUE THREAD

**Issue by Hsiang-Chih** [OWASP/wstg#465]
**What would you like added?**
It's an addition to an existing topic?  "The Web Security Testing Framework"
As I was the original author of the section, I didn't quite complete the section. I would like to add more information based on existing section. Refer here. 
https://github.com/OWASP/wstg/blob/master/document/3-The_OWASP_Testing_Framework/0-The_Web_Security_Testing_Framework.md

Here is my proposed plan.
1. Add contents for each industry methodology for the overview, methodology, and applicable tips
2. Add other methodology, FedRAMP penetration
3. Complete the exisitng "NIST800-115" contents (NIST 800-171, 800-145, 800-53, as references)

Would you like to be assigned to this issue?
I will submit a PR to add the proposed content. 
- [x] Assign me, please!

**Comment by ThunderSon** [comment]
Hi @Hsiang-Chih ! Thank you for reaching out and putting effort on this section of the guide. We'd love to receive your new content!
The section you referred to is [3.1 - Penetration Testing Methodologies](https://github.com/OWASP/wstg/blob/master/document/3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md). Let us know how we can land a hand if needed :smile:

**Comment by Hsiang-Chih** [comment]
Thank you. working on it.

**Comment by Hsiang-Chih** [comment]
Can you help to assign this issue to me again?  My mistake wrongly clicked the "assign" button.

**Comment by kingthorin** [comment]
@Hsiang-Chih are you going to be able to tackle this?

**Comment by Hsiang-Chih** [comment]
Yes working on it. Thanks to remind me again

**Comment by Hsiang-Chih** [comment]
@kingthorin I have done the updated version. How can I submit for review? refer to the attached
[1-Penetration_Testing_Methodologies.txt](https://github.com/OWASP/wstg/files/4784978/1-Penetration_Testing_Methodologies.txt)

**Comment by ThunderSon** [comment]
Hi @Hsiang-Chih 
I will provide you with the steps in the most frictionless fashion:
1. Delete your fork and create a new fork of the project.
2. [Create a new branch](https://help.github.com/en/desktop/contributing-to-projects/creating-a-branch-for-your-work)
3. Go to the directory -> `wstg/document/3-The_OWASP_Testing_Framework/1-...` It's going to be on the following URL once you fork: https://github.com/OWASP/wstg/blob/master/document/3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md
4. [Edit the file you're targeting](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository) and paste your content instead of the current existent content.
5. Come to the main repository [OWASP/wstg](https://github.com/OWASP/wstg/) and [create a Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

Hope this helps.

**Comment by Hsiang-Chih** [comment]
to create a branch I will need collaborator permissions on a repository?  Do I have the permission? @ThunderSon

**Comment by Hsiang-Chih** [comment]
"Delete your fork and create a new fork of the project."   I can't find anyway to delete the my fork on the web UI.     Do you mean delete my fork this one?  "https://github.com/Hsiang-Chih/wstg" and create a new fork of the project. "https://github.com/OWASP/wstg" ?

**Comment by Hsiang-Chih** [comment]
> Hi @Hsiang-Chih
> I will provide you with the steps to submit your work in the most frictionless fashion (hopefully):
> 
> 1. Delete your fork and create a new fork of the project.
> 2. [Create a new branch](https://help.github.com/en/desktop/contributing-to-projects/creating-a-branch-for-your-work)
> 3. Go to the directory -> `wstg/document/3-The_OWASP_Testing_Framework/1-...` It's going to be on the following URL once you fork: https://github.com/Hsiang-Chih/wstg/blob/master/document/3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md
> 4. [Edit the file you're targeting](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository) and paste your content instead of the current existent content.
> 5. Come to the main repository [OWASP/wstg](https://github.com/OWASP/wstg/) and [create a Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).
> 
> Hope this helps.

**Comment by Hsiang-Chih** [comment]
It helps. I have submitted the pull request for your review. thanks.
