### ISSUE TITLE
Sort Out "in-line" quotes/references (for which there isn't a simple link)

### ISSUE THREAD

**Issue by kingthorin** [OWASP/wstg#580]
See discussion on: https://github.com/OWASP/wstg/pull/575

The content makes reference to academic research/paper for which a link isn't available. Currently this is handled with asterisk and block quotes. Decide if we stick with that or establish/implement some other format.

**Comment by ThunderSon** [comment]
@victoriadrake I believe you'd be the best on this. I'll think about this in the coming week to see how it would look.

**Comment by victoriadrake** [comment]
Since we're increasingly moving away from the published book format (which I think makes sense for the future of this guide), in this case I would not fall back on the typical APA-style inline citation with a reference list. Whether we put the reference list at the bottom of the page or in a separate appendix, from a web usability standpoint it will be harder to find and keep updated.

With that in mind I'd advocate for a format that offers the same benefits of our inline linked resources. It should meet these criteria:

- Shows all the relevant data in one place in the text (what the source is called, who's responsible for it)
- As much as possible, not interrupt the flow of the document
- Be easy to read, understand, and translate into other languages

Since I'm not aware of a suitable standardized format that fits these criteria, I have two suggestions:

1. Leave this issue open to the community and see if anyone knows of a standard style guide for research citations that suits these criteria.
2. Avoid implementing a standard citation format for these cases at all, and instead instruct contributors to incorporate the information into the article's narration.

An example of what I mean by the latter:

> There are two possible cases: full HSTS adoption, or partial HSTS adoption. These are described in a paper called _Testing for Integrity Flaws in Web Sessions_ by Stefano Calzavara, Alvise Rabitti, Alessio Ragazzo, and Michele Bugliesi. The first case, full HSTS adoption, is when...

This form has the advantage of continuing the flow of the article and not inviting readers to jump from paragraph to paragraph, looking for an asterisk, or to another location to find a reference list. I also think it's just pleasant to read, as if learning from someone who's speaking to you, and not a dry paper.

**Comment by kingthorin** [comment]
Ya, I kinda like option 2.
