### ISSUE TITLE
SSI Injection Duplicate

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#593]
**What would you like to happen?**
The [SSI Injection test](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/08-Testing_for_SSI_Injection.md) is similar to the [OWASP common description](https://owasp.org/www-community/attacks/Server-Side_Includes_(SSI)_Injection)

@kingthorin what do you think about this?

**Comment by kingthorin** [comment]
Sure some of that content could be adapted, it doesn't seem vastly different but some of it is usable.

**Comment by ThunderSon** [comment]
So I guess the best way forward is to clean up the test scenario, link the general link inside the test, and go into methodologies?
Or what do you think?

**Comment by n17h31sm** [comment]
I looked over the 2 pages and in my opinion we can improve it in the following way:

- Remove/Cut the 2 paragraphs before the 'How to test' part, because they are essentially just repeating what was already said in the introduction, there are just a couple bits of information that are meaningful and probably can be put in the introduction or just in more concise form. 

- Otherwise SSI isn't complex so we can't really have something so vastly different. But we can link a cheatsheet or page with the possible options/commands instead of listing the test cases. 

- Also the methodologies I think we can expand and mention some more possibilities. 

I am also up for taking the issue as my first on WSTG.

**Comment by kingthorin** [comment]
Sounds good to me.
