### ISSUE TITLE
Set Testing Objectives For All Test Scenarios

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#602]
**What's the issue?**
Not all testing scenarios have a clear and concise objective(s)

**How do we solve it?**
Go over the WSTG and ensure that every test scenario has clear objectives in a UL format (using dashes).

Since this is one of the bigger issues and will cover lots of scenarios, I'll tackle it and make sure to make it fast.

**Comment by patrickceg** [comment]
I could look at this if no one else takes it on **November 20th, 2020**.
My goal with this project is to help make the guide accessible to people new to testing, so I like this type of task.

In the meantime, what should we consider a good testing objective, so that when we go through the guide, we can also mark tests that need an improved objective section (but not necessarily missing it completely)?

**Comment by kingthorin** [comment]
There’s an initial PR in already for the first bunch of sections/scenarios.

**Comment by ThunderSon** [comment]
@patrickceg Hi Patrick. I am handling them as I need them under a certain format and need. Thanks for the help offer! :)
