### ISSUE TITLE
EPUB version

### ISSUE THREAD

**Issue by zanardigit** [OWASP/wstg#729]
Hello and thank you for this excellent and extremely useful resource!

Is there any plan / WIP about an EPUB version of the guide? Or is there anyone who would be interested in wokring on it?

**Comment by kingthorin** [comment]
There isn’t currently any plan for an epub version, however we could investigate if there’s a simple way to convert the PDF.

**Comment by zanardigit** [comment]
I already did a test about PDF to EPUB conversion, but PDF is a very difficult format to convert from and the quality of the result is very low. I'm now testing with `pandoc` from MD sources, and it looks like we're getting somewhere. Attached you can find a no-image EPUB version which took only a few minutes to create.

I will spend a little more time on it to see if I can include images as well and then share the process. Thank you!

[wstg.zip](https://github.com/OWASP/wstg/files/6175509/wstg.zip)

**Comment by ThunderSon** [comment]
That's an interesting proposal. So before we make this into a PDF, we do some magic to transform the headers and the figures into parseable entities, so that we can reference them across the document and have the links activate like you'd be doing on the web interface. So clicking on "Chapter 4.1.5" would take you there, and not just be a reference to where they can find it.

As we've seen, the engines that transform MD to PDF/EPUB don't provide that.

Our logic is in the `.github` directory with several separate scripts that take care of making things happen.

cc: @rejahrehim

**Comment by victoriadrake** [comment]
I think this would be a welcome addition @zanardigit if we can find a smooth automated way to generate it.

**Comment by zanardigit** [comment]
Cannot make any promise, but I'll keep this on the radar and see what I can do. I guess I will ask on Slack if I need additional informations.

**Comment by victoriadrake** [comment]
This could come in handy: https://news.ycombinator.com/item?id=26898591

**Comment by rejahrehim** [comment]
@ThunderSon I can take this. Let me try and come up with a plan

**Comment by kingthorin** [comment]
@rejahrehim I believe @zanardigit is already working on it, per the earlier comments.

**Comment by zanardigit** [comment]
@kingthorin @ThunderSon @rejahrehim I haven't done anything yet so if anyone is willing and ready to go, they're welcome. Not much spare time in these period unfortunately.

**Comment by kingthorin** [comment]
@zanardigit no problem, thanks for letting us know.

**Comment by saigoud25** [comment]
Can I work on this. The task is to convert PDF to EPUB right?

**Comment by kingthorin** [comment]
Well it doesn’t have to be from the PDF, though that might be easiest.
